---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: 18fgsa/concourse-task
    registry_mirror:
      host: docker-registry-mirror.app.cloud.gov:443

inputs:
- name: cf-manifests
outputs:
- name: integration-config

run:
  path: cf-manifests/ci/acceptance-tests-config.sh
