environment: production
system_domain: fr.cloud.gov

buildpack_directory_key: cf-production-buildpacks
droplet_directory_key: cf-production-droplets
app_package_directory_key: cf-production-cc-packages
resource_directory_key: cf-production-cc-resources
