environment: staging
network_name: default
deployment_name: cf-staging
company-name: cloud.gov staging
system_domain: fr-stage.cloud.gov
app_domain: fr-stage.cloud.gov

buildpack_directory_key: cf-staging-buildpacks
droplet_directory_key: cf-staging-droplets
app_package_directory_key: cf-staging-cc-packages
resource_directory_key: cf-staging-cc-resources

disable_internal_user_management: true